### ISSUE TITLE
The future of Fifo on Windows 7 and Windows 8.1

### ISSUE THREAD

**Issue by 97tn** [snaildos/Fifo-Browser#218]
As of 110 release, Chromium dropped support for Windows 7 and Windows 8.1. Electron is Chromium based, so Electron will follow Chromium. The last version of Chromium working on Windows 7 and Windows 8.1 is 109.

**Comment by snaildos** [comment]
That is correct. Fifo will EOL on Windows 7 and 8.1 systems.

**Comment by 97tn** [comment]
> That is correct. Fifo will EOL on Windows 7 and 8.1 systems.

What about making a last version for Windows 7 and 8.1 systems (with an Electron version based on Chromium 109)?

**Comment by snaildos** [comment]
> > That is correct. Fifo will EOL on Windows 7 and 8.1 systems.
> 
> What about making a last version for Windows 7 and 8.1 systems (with an Electron version based on Chromium 109)?

Since we have essentially finished the update already for Chrome version 109+ I probably will be not releasing a lower version. I do not advice you to stick on Windows 7 or 8.1 since these are EOL. I do advice you however to maybe look into our upcoming Linux operating system that will be released to general public very soon. It is private by default. 👀
