### ISSUE TITLE
Suggestion: HTTPS-Only mode

### ISSUE THREAD

**Issue by MrDiamond64** [snaildos/Fifo-Browser#52]
**Is your feature request related to a problem? Please describe.**
The HTTP protocol is extremely insecure and outdated (sends all traffic in plain text). 

**Describe the solution you'd like**
If the website your trying to connect to is HTTP, check if there's a HTTPS version available, if not warn the user of a security risk.

**Describe alternatives you've considered**
HTTPSEverywhere addon 

**Additional context**
SnailDOS likes security so this should be an obvious feature to add.

**Comment by snaildos** [comment]
I just read through the code and this is not possible unless someone else can help. If I do add this feature, Fifo may be unstable and not optimized since there isn't any http or https checkes implemented in the backend of it. 
I did, however, add when hovering over the tab with http, it will say "Unsecure Website".

**Comment by snaildos** [comment]
We're going to add an warning for unsecure websites.
Thank you for your suggestion.
Should be in the next release after this one.

**Comment by snaildos** [comment]
We added invalid certificate warnings and will be adding the well known padlock icon in the next release.
Thank you for your suggestion!
