### ISSUE TITLE
Known issues for next release.

### ISSUE THREAD

**Issue by snaildos** [snaildos/Fifo-Browser#93]
- [x] Tab grouping configuration
- [x] News on rare occasion just breaks.
- [x] Fix notification dialogue bug
- [x] Dialogues are faulty (newtab, bookmark edit)
- [x] Favicon storage prior v1.1.0 is corrupted, this update needs to tell users that its going to erase the favicon index.
- [x] Duplicate Tab button not working on QuickMenu
- [x] Change Search Engine
- [x] Clear Permissions database option
- [x] Zoom does not work
- [x] Download manage does not show correctly
This will be released after v1.2.0 release.

**Comment by snaildos** [comment]
*Checklist applies to version v1.2.1

**Comment by snaildos** [comment]
https://github.com/snaildos/Fifo-Browser/tree/1.2.1
Working in this branch.

**Comment by 3oheicrw** [comment]
Please add Exit to the menu like Chromium based browser. It's really useful. Currently the last entry on the menu on Fifo is Print.

**Comment by 3oheicrw** [comment]
More about favicon. It seems only png favicon is reliably saved. Favicon in other formats sometimes works sometime not. Also, site's favicon is not updated if you revisit the link nor reload the page. It's always the favicon saved when you first open the link. If that saved favicon is corrupt, then it's no way to update it.

https://en.wikipedia.org/wiki/Favicon

**Comment by 3oheicrw** [comment]
About bookmarks, it seems currently we can only put bookmarks in the bookmark bar. There is an dialog asking where to put the bookmark like on Chrome but it's only possible to choose "Bookmarks bar". When going to bookmarks manager, I found it's impossible to move the bookmarks by dragging them. Same for the bookmark bar. Chrome's bookmark bar could have bookmark dragged to new location without having to open bookmarks manager.

**Comment by 3oheicrw** [comment]
On bookmarks manager, I can select the bookmarks but can only operate on it via right click. Unlike on Chrome I could select the bookmarks and delete them via Delete key in the keyboard. Chrome supports shortcut keys like Ctrl + C, Ctrl + X and Ctrl + V too but I think it's not really needed. The most important to implement is able to delete bookmarks by the Delete key in keyboard and the ability to move them by dragging.

**Comment by 3oheicrw** [comment]
Just discovered that adblocker doesn't work in Incognito window.

**Comment by 3oheicrw** [comment]
Investigating on the exported to html bookmarks of Fifo and Firefox. I found Fifo only put ICON= that contains the base64 encoding of the favicon but, doesn't have ICON_URI, ADD_DATE and LAST_MODIFIED. I also found I can't select more than one bookmark on Fifo's bookmarks manager, on Chrome and Firefox I could use Ctrl or Shift to select multiple bookmarks.

**Comment by 3oheicrw** [comment]
Please consider provide an option in Settings to disable media autoplay. This option is available as a built-in option in Chrome and Firefox. I realized how little we could control in Electron. I have talked with another Electron based browser developer. He said he can't do anything much with Electron than a customized shiny graphical interface and he is about to switch to native (Qt with QtWebEngine). If this is the inherent limitations of Electron then I'm sorry because I have asked for too much. I'm not really know about that. I only think I'm giving feedbacks but don't know if it's annoying you, for many things you can't take control.

**Comment by snaildos** [comment]
Hi, thanks for these issues. However, you are comparing Fifo to chrome. Please know I am the only active maintaner of this project and I have already spent 6+ hours in the past 2 days working on this project. It is really hard for you to compare this large codebase with chrome. However, the simple feedback is appreciated and bug reports are great. I will not be adding order to bookmarks nor adding an option to select bookmarks _at this time_. As I said, we need more project maintainers as this is getting fairly stressful for me. I will be implimenting the basic feedback to try and push this bugfix out of the way.

**Comment by snaildos** [comment]
Previously I planned an option to change search engines and I am now confirming this change will not be haplening due to the configuration required by the user to do so. We are not declining search engine suggestions however, feel free to request custom engines as you see fit.

**Comment by 3oheicrw** [comment]
> Previously I planned an option to change search engines and I am now confirming this change will not be haplening due to the configuration required by the user to do so. We are not declining search engine suggestions however, feel free to request custom engines as you see fit.

Search suggestion is just broken. Even suggestions from history. As I said, instead of youtube.com it's suggesting something like https://www.youtube.com/results?search_query=wwe+highlights. Even more weirded, when I search for something it suggested something else. For example, I searched my mechanic youtube, it's suggesting me with freebsd forums (previously searched from the address bar by me and totally unrelated to what I'm searching). IMO, if you can't get it right, provide a way for the user to disable it before you could fix it.

About search engine, Google is currently broken. It's broken because it keeps asking for my location and the notification dialog doesn't disappear until I close this tab (even after you quit Google and browsing something else, still this notification dialog asking for your location). I'm not yet try Bing and Ecosia, but the default DuckDuckGo seems to be the only thing that works right, since it doesn't ask for your location. I don't think you to add more search engines. You should focus to fix the bugs first.

**Comment by 3oheicrw** [comment]
> Hi, thanks for these issues. However, you are comparing Fifo to chrome. Please know I am the only active maintaner of this project and I have already spent 6+ hours in the past 2 days working on this project. It is really hard for you to compare this large codebase with chrome.

Not actually. I use Chrome and Firefox as the reference for UI designs and only UI designs. I don't compare Fifo with Chrome or Firefox without that context. BTW I'm sorry if I put a lot of stress on you.

**Comment by snaildos** [comment]
> > Previously I planned an option to change search engines and I am now confirming this change will not be haplening due to the configuration required by the user to do so. We are not declining search engine suggestions however, feel free to request custom engines as you see fit.
> 
> Address bar suggestions is just broken (not only search suggestions). Even suggestions from history. As I said, instead of youtube.com it's suggesting something like https://www.youtube.com/results?search_query=wwe+highlights. Even more weirded, when I search for something it suggested something else. For example, I searched my mechanic youtube, it's suggesting me with freebsd forums (previously searched from the address bar by me and totally unrelated to what I'm searching). IMO, if you can't get it right, provide a way for the user to disable it before you could fix it.
> 
> About search engine, Google is currently broken. It's broken because it keeps asking for my location and the notification dialog doesn't disappear until I close this tab (even after you quit Google and browsing something else, still this notification dialog asking for your location). I'm not yet try Bing and Ecosia, but the default DuckDuckGo seems to be the only thing that works right, since it doesn't ask for your location. I don't think you should add more search engines. You should focus to fix the bugs first.

This is patched in the latest version that is not released to general public yet.

**Comment by snaildos** [comment]
![image](https://user-images.githubusercontent.com/46210117/178902679-0d3c90b3-9927-4f15-bec3-411c3069dda0.png)
New Zoom UI

**Comment by snaildos** [comment]
![image](https://user-images.githubusercontent.com/46210117/178902715-8e2ead73-aafc-4924-9013-8c0ba56edddc.png)
![image](https://user-images.githubusercontent.com/46210117/178902744-f6e30588-1860-406c-b92b-e98906927fa0.png)
